##
# This is the CI/CD workflow for the firebase functions.
# Pre-requisites:
# These tokes are stored in the secrets.
# 1. FIREBASE_TOKEN : ci token obtained via firebase login:ci
# 2. The project id similar to the .firebaserc file 
#    2.1 FIREBASE_DEV_PROJECT_ID : project id for deploying to the DEV environment
#    2.2 FIREBASE_UAT_PROJECT_ID : project id for deploying to the UAT environment
#    2.3 FIREBASE_PROD_PROJECT_ID : project id for deploying to the PROD environment
##
name: ci/cd

on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop, test, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  cicd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ''
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: npm i -g get-graphql-schema
      - run: get-graphql-schema --version
      - run: flutter test
      - run: flutter build web --release

      - name: Deploy to PROD environment
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env: 
            FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
            PROJECT_ID: ${{secrets.FIREBASE_DEV_PROJECT_ID}}    
